/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/pockost/sshpipe-k8s-lib/pkg/apis/pockost.com/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSshPipes implements SshPipeInterface
type FakeSshPipes struct {
	Fake *FakePockostV1beta1
	ns   string
}

var sshpipesResource = schema.GroupVersionResource{Group: "pockost.com", Version: "v1beta1", Resource: "sshpipes"}

var sshpipesKind = schema.GroupVersionKind{Group: "pockost.com", Version: "v1beta1", Kind: "SshPipe"}

// Get takes name of the sshPipe, and returns the corresponding sshPipe object, and an error if there is any.
func (c *FakeSshPipes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.SshPipe, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sshpipesResource, c.ns, name), &v1beta1.SshPipe{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.SshPipe), err
}

// List takes label and field selectors, and returns the list of SshPipes that match those selectors.
func (c *FakeSshPipes) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.SshPipeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sshpipesResource, sshpipesKind, c.ns, opts), &v1beta1.SshPipeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.SshPipeList{ListMeta: obj.(*v1beta1.SshPipeList).ListMeta}
	for _, item := range obj.(*v1beta1.SshPipeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sshPipes.
func (c *FakeSshPipes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sshpipesResource, c.ns, opts))

}

// Create takes the representation of a sshPipe and creates it.  Returns the server's representation of the sshPipe, and an error, if there is any.
func (c *FakeSshPipes) Create(ctx context.Context, sshPipe *v1beta1.SshPipe, opts v1.CreateOptions) (result *v1beta1.SshPipe, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sshpipesResource, c.ns, sshPipe), &v1beta1.SshPipe{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.SshPipe), err
}

// Update takes the representation of a sshPipe and updates it. Returns the server's representation of the sshPipe, and an error, if there is any.
func (c *FakeSshPipes) Update(ctx context.Context, sshPipe *v1beta1.SshPipe, opts v1.UpdateOptions) (result *v1beta1.SshPipe, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sshpipesResource, c.ns, sshPipe), &v1beta1.SshPipe{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.SshPipe), err
}

// Delete takes name of the sshPipe and deletes it. Returns an error if one occurs.
func (c *FakeSshPipes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(sshpipesResource, c.ns, name), &v1beta1.SshPipe{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSshPipes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sshpipesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.SshPipeList{})
	return err
}

// Patch applies the patch and returns the patched sshPipe.
func (c *FakeSshPipes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.SshPipe, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sshpipesResource, c.ns, name, pt, data, subresources...), &v1beta1.SshPipe{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.SshPipe), err
}
